### ISSUE TITLE
make all won't install dependencies

### ISSUE THREAD

**Issue by Phyps105** [muslimitmilch/minceraft#5]
Although the readme suggests, that `make all` would also install minceraft_launcher_lib and msmcauth, minceraft proceeds to crash as it could not find the minceraft_launcher_lib module.
The issue seems to be, that the makefile requires pip to be installed.

**To Reproduce**
 - clone the repo
 - make all
 - make install
 - start minceraft

**Expected behavior**
make actually will actually install  msmcauth and minecraft-launcher-lib launcher lib, regardless of pip being installed beforehand or not  (I really wanna play minceraft on my lappytoppy :) )

**Desktop**
 - Fedora 41

**Comment by CdrJohannsen** [comment]
pip can't and should not be installed by the Makefile. 

However, i've changed the Readme to mention this dependency.
